In [1]:
from sklearn.linear_model import LogisticRegression

In [2]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [15]:
#supress warnings
import warnings 
warnings.filterwarnings('ignore')

In [3]:
digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split

In [10]:
X = digits.data

y = digits.target

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [16]:
lr = LogisticRegression()

lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9685185185185186

In [17]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.39814814814814814

In [18]:
rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

# Cross Val score is good way to compare different models

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
# cross val score for logistic regression
cross_val_score(LogisticRegression(),X,y)

array([0.89534884, 0.94991653, 0.90939597])

In [21]:
# cross val score for SVM
cross_val_score(SVC(),X,y)

array([0.39368771, 0.41068447, 0.45973154])

In [25]:
#cross val score for Random Forest classifier
cross_val_score(RandomForestClassifier(n_estimators= 45),X,y)

array([0.92524917, 0.95325543, 0.92449664])